name: tbh-postgresql
services:
  postgresql:
    image: postgres:16
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - ${POSTGRES_PORT}:5432
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_data:
    name: postgres_data

networks:
  postgres_network:
    name: postgres_network
