name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/server:${{ github.run_number }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: deploy
        run: |
          cd /home/ubuntu
          sudo chmod +x ./deploy.sh
          sudo ./deploy.sh
