name: backend deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name : create .env file
        run : echo "${{secrets.env}}" >> .env

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.5

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      # Docker Build & Push
      - name: Docker Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/server:${{github.run_number}}
            ${{ secrets.DOCKER_HUB_USERNAME }}/server:latest

deploy:
  runs-on: self-hosted
  steps:
    - name: change permission
      run: |
        sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/server
    - uses: actions/checkout@v3

    - name: deploy
      run: cd /home/ubuntu && sudo ./deploy.sh
